import type { Metadata } from "next"
import { AppAlert, GradientBackground } from "@/components"
import "./globals.css"



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <GradientBackground />
        <AppAlert />
        {children}
      </body>
    </html>
  )
}
