import localFont from "next/font/local"
import type { Metadata } from "next"
import "./globals.css"


const unbounded = localFont({ src: "./fonts/Unbounded-VariableFont.ttf" })
const montserrat = localFont({ src: "./fonts/Montserrat-VariableFont.ttf" })


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}



export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${unbounded.className} ${montserrat.className}`}>
        {children}
      </body>
    </html>
  )
}
